#!/usr/bin/env python3
"""Traducteur de chaînes chinoises vers clés i18n pour Kraxia."""
import os, re, sys

ROOT = '/home/user/ops/frontend/src'

# Map: substring matching → i18n TT(...) key
# These are full-line replacements only when a hardcoded Chinese label is found.
TR = [
  # Brand & nav
  ('OpenClaw AI', "tr('brand.name')"),
  ('Multi User OpenClaw v2026.04.11', "tr('brand.version')"),
  ('OpenClaw', "tr('brand.name')"),
  ('openclaw', "kraxia"),
  ('仪表盘', 'tableau de bord'),
  ('Agents 管理', 'Gestion des agents'),
  ('技能商店', 'Bibliothèque de compétences'),
  ('渠道管理', 'Canaux de communication'),
  ('插件管理', 'Gestion des extensions'),
  ('AI 模型', 'Modèles IA'),
  ('文件管理', 'Gestionnaire de fichiers'),
  ('知识库', 'Base de connaissances'),
  ('实时终端', 'Terminal temps réel'),
  ('会话历史', 'Historique des conversations'),
  ('定时任务', 'Tâches planifiées'),
  ('Node 管理', 'Gestion des nœuds'),
  ('API设定', 'Accès API'),
  ('API 设定', 'Accès API'),
  ('系统设置', 'Paramètres système'),
  ('概览', "Vue d'ensemble"),
  ('技能中心', 'Centre de compétences'),
  ('系统', 'Système'),
  ('仪表盘', 'Tableau de bord'),
  # Hero login
  ('用户名或邮箱', "Nom d'utilisateur ou email"),
  ('用户名', "Nom d'utilisateur"),
  ('密码', 'Mot de passe'),
  ('邮箱', 'Adresse email'),
  ('登录', 'Se connecter'),
  ('注册', "S'inscrire"),
  ('还没有账号？', 'Pas encore de compte ?'),
  ('已有账号？', 'Déjà un compte ?'),
  ('MedClaw 医疗智能助手', 'Kraxia — Assistant IA'),
  ('密码登录', 'Connexion par mot de passe'),
  ('登录中...', 'Connexion en cours...'),
  ('请输入用户名', 'Saisissez votre nom d\'utilisateur'),
  ('请输入密码', 'Saisissez votre mot de passe'),
  ('使用您的账号密码登录', 'Connectez-vous avec votre identifiant et mot de passe'),
  ('登录失败', 'Échec de la connexion'),
  ('An unexpected error occurred', "Une erreur inattendue s'est produite"),
  # Sidebar
  ('修改密码', 'Modifier le mot de passe'),
  ('退出登录', 'Se déconnecter'),
  ('旧密码', 'Ancien mot de passe'),
  ('新密码', 'Nouveau mot de passe'),
  ('确认新密码', 'Confirmer le nouveau mot de passe'),
  ('请输入旧密码', "Saisissez l'ancien mot de passe"),
  ('至少6个字符', 'Au moins 6 caractères'),
  ('再次输入新密码', 'Saisissez à nouveau le nouveau mot de passe'),
  ('确认修改', 'Confirmer la modification'),
  ('密码修改成功', 'Mot de passe modifié avec succès'),
  ('新密码至少需要6个字符', 'Le nouveau mot de passe doit contenir au moins 6 caractères'),
  ('两次输入的新密码不一致', 'Les mots de passe ne correspondent pas'),
  ('请输入旧密码', "Saisissez l'ancien mot de passe"),
  ('旧密码不正确', 'Ancien mot de passe incorrect'),
  ('修改失败', 'Échec de la modification'),
  # Status
  ('服务初始化中', "Service en cours d'initialisation"),
  ('服务运行中', 'Service opérationnel'),
  ('服务离线', 'Service hors ligne'),
  # Topbar
  ('系统设置', 'Paramètres système'),
  ('退出登录', 'Se déconnecter'),
  # Theme
  ('切换暗色主题', 'Passer au thème sombre'),
  ('切换亮色主题', 'Passer au thème clair'),
  # Brand subtitle
  ('Multi User OpenClaw v2026.04.11', "Kraxia SaaS multi-tenant d'agents IA"),
  # Dashboard
  ('Agent 运行总览', "Vue d'ensemble des agents"),
  ('处理中', 'En cours'),
  ('最近活跃', 'Actif récemment'),
  ('空闲', 'Inactif'),
  ('Agent 总数', "Nombre total d'agents"),
  ('会话总数', 'Conversations'),
  ('技能总数', 'Compétences'),
  ('Agents Overview', "Aperçu des agents"),
  ('查看全部', 'Tout afficher'),
  ('Agent 名称', "Nom de l'agent"),
  # Agents
  ('管理和配置您的 AI Agents', 'Administrer et configurer vos agents IA'),
  ('新建 Agent', 'Créer un agent'),
  ('搜索 Agent 名称或 ID...', "Rechercher un agent par nom ou ID..."),
  ('详情', 'Détails'),
  ('删除', 'Supprimer'),
  ('确定删除该 Agent？', 'Confirmer la suppression de cet agent ?'),
  # AgentCreate
  ('返回 Agent 列表', 'Retour à la liste'),
  ('创建 Agent', "Créer l'agent"),
  ('取消', 'Annuler'),
  ('新建 Agent', 'Créer un agent'),
  ('配置并创建新的 AI Agent', 'Configurer et créer un nouvel agent IA'),
  ('显示名称 *', 'Nom affiché *'),
  ('Agent ID *', "Identifiant de l'agent *"),
  ('工作区路径', 'Chemin du workspace'),
  ('留空则自动生成', 'Laisser vide pour générer automatiquement'),
  ('仅支持小写字母、数字、下划线和连字符（a-z, 0-9, _, -）', "Lettres minuscules, chiffres, tirets et underscores (a-z, 0-9, _, -)"),
  ('— 请手动输入英文 ID', "— Veuillez saisir un identifiant en anglais"),
  ('例如：保险智能体、Customer Support', "ex : Assistant Service Client, Customer Support"),
  ('创建后将调用：', 'Appel à la création :'),
  ('创建失败，请重试', 'Échec de la création, veuillez réessayer'),
  ('保险智能体、Customer Support', "Assistant Service Client, Customer Support"),
  ('insurance-agent', 'mon-agent'),
  # Sessions
  ('查看所有 Agent 的对话记录', 'Consulter toutes les conversations'),
  ('刷新', 'Actualiser'),
  ('暂无会话记录', 'Aucun historique'),
  ('会话', 'Conversation'),
  ('创建时间', 'Créée le'),
  ('最近更新', 'Dernière mise à jour'),
  ('查看会话', 'Voir la conversation'),
  ('删除会话', 'Supprimer la conversation'),
  ('确定删除该会话？', 'Confirmer la suppression de cette conversation ?'),
  ('条消息', 'messages'),
  ('创建于', 'Créée le'),
  ('暂无消息记录', 'Aucun message'),
  ('(空消息)', '(message vide)'),
  # CronJobs
  ('定时任务', 'Tâches planifiées'),
  ('新建任务', 'Nouvelle tâche'),
  ('暂无定时任务，点击「新建任务」开始创建', 'Aucune tâche. Cliquez sur « Nouvelle tâche » pour commencer.'),
  ('任务名称', 'Nom de la tâche'),
  ('调度', 'Planification'),
  ('上次执行', 'Dernière exécution'),
  ('下次执行', 'Prochaine exécution'),
  ('操作', 'Actions'),
  ('固定间隔', 'Intervalle fixe'),
  ('Cron 表达式', 'Expression cron'),
  ('单次执行', 'Exécution unique'),
  ('间隔秒数 (>0)', 'Intervalle en secondes (>0)'),
  ('名称', 'Nom'),
  ('消息', 'Message'),
  ('可选：任务完成后通知指定渠道', 'Optionnel : notifier un canal après exécution'),
  ('保存', 'Enregistrer'),
  ('创建定时任务失败', "Échec de la création de la tâche"),
  # Channels
  ('接口接入', "Connexion d'interface"),
  ('刷新', 'Actualiser'),
  ('渠道', 'Canal'),
  ('已配置渠道', 'Canaux configurés'),
  ('可用渠道', 'Canaux disponibles'),
  ('点击「配置」开始接入', 'Cliquez sur « Configurer » pour commencer'),
  ('配置', 'Configurer'),
  ('删除', 'Supprimer'),
  ('确定要删除该渠道吗？', 'Confirmer la suppression de ce canal ?'),
  ('重新启动网关使插件生效', 'Redémarrez la passerelle pour appliquer'),
  ('正在保存', 'Enregistrement...'),
  ('点击「微信」渠道绑定', 'Lier le canal WeChat'),
  ('微信绑定说明', 'Instructions de liaison WeChat'),
  # Plugins
  ('安装新插件', 'Installer une nouvelle extension'),
  ('通过 npm 安装第三方插件', 'Installer une extension tierce via npm'),
  ('已安装插件', 'Extensions installées'),
  ('可用插件', 'Extensions disponibles'),
  ('点击安装', 'Installer'),
  ('确认卸载该插件？', 'Confirmer la désinstallation ?'),
  # SkillStore
  ('技能列表', 'Liste des compétences'),
  ('上传技能 ZIP', 'Téléverser un ZIP de compétences'),
  ('从 Git 仓库导入', 'Importer depuis un dépôt Git'),
  ('扫描 Git 仓库', 'Scanner un dépôt Git'),
  ('已安装', 'Installée'),
  ('推荐技能', 'Compétences recommandées'),
  ('按类别浏览', 'Parcourir par catégorie'),
  ('安装失败', "Échec de l'installation"),
  ('安装成功', 'Installation réussie'),
  # Models
  ('模型配置', 'Configuration des modèles'),
  ('添加模型', 'Ajouter un modèle'),
  ('删除模型', 'Supprimer un modèle'),
  ('添加新供应商', 'Ajouter un fournisseur'),
  ('编辑供应商', 'Modifier le fournisseur'),
  ('已配置供应商', 'Fournisseurs configurés'),
  ('API 类型', "Type d'API"),
  ('OpenAI Completions', 'OpenAI Completions'),
  ('OpenAI Responses', 'OpenAI Responses'),
  ('Anthropic Messages', 'Anthropic Messages'),
  ('Google Generative AI', 'Google Generative AI'),
  ('Ollama', 'Ollama'),
  ('AWS Bedrock', 'AWS Bedrock'),
  ('国际服务', 'Services internationaux'),
  ('国内服务', 'Services chinois'),
  ('本地部署', 'Déploiement local'),
  ('自定义', 'Personnalisé'),
  ('默认模型已设置为', 'Modèle par défaut défini sur '),
  ('设置失败', 'Échec de la configuration'),
  ('提供商', 'Fournisseur'),
  ('模型', 'Modèle'),
  # Files
  ('文件夹', 'Dossier'),
  ('文件', 'Fichier'),
  ('返回上一级', 'Remonter'),
  ('新建文件夹', 'Nouveau dossier'),
  ('上传文件', 'Téléverser'),
  ('下载', 'Télécharger'),
  ('大小', 'Taille'),
  ('修改时间', 'Modifié le'),
  ('当前路径', 'Chemin actuel'),
  # Terminal
  ('启动命令，例如 bash -il', 'ex : bash -il'),
  ('连接', 'Connecter'),
  ('断开', 'Déconnecter'),
  ('清屏', 'Effacer'),
  ('已连接', 'Connecté'),
  ('未连接', 'Non connecté'),
  ('未登录或 token 已失效', 'Non connecté ou jeton expiré'),
  # Nodes
  ('已配对节点', 'Nœuds appairés'),
  ('已批准的配对请求', 'Demandes approuvées'),
  ('待审批请求', 'Demandes en attente'),
  ('审批通过', 'Approuver'),
  ('拒绝', 'Rejeter'),
  ('节点 ID', 'ID du nœud'),
  ('远程地址', 'Adresse distante'),
  ('权限', 'Permissions'),
  ('添加新节点', 'Ajouter un nœud'),
  ('通过命令行', 'Via ligne de commande'),
  ('通过 macOS 菜单栏', 'Via barre de menu macOS'),
  ('通过 SSH 隧道', 'Via tunnel SSH'),
  ('重新加载', 'Recharger'),
  # ApiAccess
  ('生成 API 令牌', 'Générer un jeton API'),
  ('令牌有效期', 'Validité'),
  ('天', 'jours'),
  ('CLI 使用示例', "Exemple d'utilisation CLI"),
  ('Python 调用示例', 'Exemple d\'appel Python'),
  ('复制命令', 'Copier la commande'),
  ('已复制', 'Copié'),
  ('请妥善保管，关闭页面后无法再次查看完整令牌', 'Conservez-le, le jeton complet ne sera plus affiché'),
  # Settings
  ('管理 OpenClaw 网关配置', 'Administrer la configuration de la passerelle Kraxia'),
  ('网关状态', 'État de la passerelle'),
  ('保存设置', 'Enregistrer'),
  ('保存后请点击上方「重启网关」使配置生效', 'Après enregistrement, cliquez sur « Redémarrer la passerelle » pour appliquer'),
  ('已连接', 'Connectée'),
  ('未连接', 'Non connectée'),
  ('配置文件', 'Fichier de configuration'),
  ('工作区', 'Workspace'),
  ('当前模型', 'Modèle actuel'),
  ('容器信息', 'Informations sur le conteneur'),
  ('容器名称', 'Nom du conteneur'),
  ('容器状态', 'État du conteneur'),
  ('创建时间', 'Créé le'),
  ('端口映射', 'Mappage de ports'),
  ('端口', 'Port'),
  ('网关配置', 'Configuration de la passerelle'),
  ('绑定地址', 'Adresse de liaison'),
  ('loopback (仅本机)', 'loopback (machine locale uniquement)'),
  ('all (所有接口)', 'all (toutes les interfaces)'),
  ('允许的来源（CORS）', 'Origines autorisées (CORS)'),
  ('每行一个 URL，用于 Control UI 的跨域访问控制', 'Une URL par ligne, pour CORS'),
  ('关于', 'À propos'),
  ('平台版本', 'Version'),
  ('认证模式', "Mode d'authentification"),
  ('数据目录', 'Répertoire de données'),
  ('一键修复', 'Réparation automatique'),
  ('修复中...', 'Réparation en cours...'),
  ('修复完成，容器已自动重启', 'Réparation terminée, conteneur redémarré'),
  ('修复命令返回非零退出码，请查看输出详情', 'La commande a renvoyé un code non nul'),
  ('修复结果 (exit code:', 'Résultat (code de sortie :'),
  ('暂无容器', 'Aucun conteneur'),
  ('运行中', 'En cours'),
  ('异常重启中', 'Redémarrage anormal'),
  ('创建中', 'Création'),
  ('已暂停', 'En pause'),
  ('已停止', 'Arrêté'),
  ('已归档', 'Archivé'),
  ('遇到问题时，可将容器名称告知管理员协助排查。如果容器配置损坏导致无法启动，请点击「一键修复」。', "En cas de problème, indiquez le nom du conteneur à l'administrateur. Cliquez sur « Réparation automatique » si la configuration est corrompue."),
  ('重启网关', 'Redémarrer la passerelle'),
  ('重启中...', 'Redémarrage en cours...'),
  ('设置已保存，请点击「重启网关」使配置生效', 'Paramètres enregistrés, cliquez sur « Redémarrer la passerelle » pour appliquer'),
  ('修复失败', 'Échec de la réparation'),
  ('网关已重启', 'Passerelle redémarrée'),
  # Audit Log
  ('审计日志', "Journal d'audit"),
  ('系统操作和安全事件记录', 'Opérations système et événements de sécurité'),
  ('完成市场调研报告生成', "Génération d'un rapport d'étude de marché"),
  ('生成 PDF 报告并发送至企业微信', 'Rapport PDF généré et envoyé sur WeChat Entreprise'),
  ('CPU 使用率超过阈值', "Utilisation CPU au-dessus du seuil"),
  ('服务器 prod-web-03 CPU 达到 92%', 'Serveur prod-web-03 CPU à 92%'),
  ('客户方案生成完成', 'Proposition client générée'),
  ('为客户 #A2089 生成定制方案', 'Proposition personnalisée pour client #A2089'),
  ('合同解析完成', 'Analyse de contrat terminée'),
  ('成功提取 23 个关键条款', '23 clauses clés extraites'),
  ('异常登录检测', "Tentative de connexion inhabituelle"),
  ('来自未知 IP 的登录尝试已拦截', 'Connexion depuis une IP inconnue bloquée'),
  ('每日数据备份完成', 'Sauvegarde quotidienne terminée'),
  ('备份大小 2.3 GB', 'Sauvegarde de 2.3 Go'),
  ('响应延迟超过阈值', 'Latence au-dessus du seuil'),
  ('平均响应时间 1.8s，阈值 1.5s', 'Latence moyenne 1.8s, seuil 1.5s'),
  ('流水线部署成功', 'Pipeline déployé'),
  ('v2.3.1 已部署至 staging 环境', 'v2.3.1 déployé en staging'),
  ('来源:', 'Source :'),
  ('今天', "aujourd'hui"),
  ('Nova-Alpha 01', 'Nova-Alpha 01'),
  ('DevOps-Bot 02', 'DevOps-Bot 02'),
  ('Sales-AI 03', 'Sales-AI 03'),
  ('Doc-Parser 04', 'Doc-Parser 04'),
  ('Security-Guard 05', 'Security-Guard 05'),
  ('系统', 'Système'),
  # Notifications
  ('通知', 'Notifications'),
  ('对话完成后会出现在这里', 'Vos conversations terminées apparaîtront ici'),
  ('全部已读', 'Tout marquer comme lu'),
  ('暂无通知', 'Aucune notification'),
  ('分钟前', ' min'),
  ('小时前', ' h'),
  ('天前', ' j'),
  (' Agent ', ' agent '),
  (' 对话已完成', ' Conversation terminée'),
  ('对话已完成', 'Conversation terminée'),
  ('删除通知', 'Supprimer'),
  # Tools
  ('加载技能', 'Chargement de compétence'),
  ('执行命令', 'Exécution de commande'),
  ('查看文件', 'Lecture de fichier'),
  ('写入文件', 'Écriture de fichier'),
  ('编辑文件', 'Édition de fichier'),
  ('列出技能', 'Liste des compétences'),
  ('网络搜索', 'Recherche web'),
  ('浏览网页', 'Navigation web'),
  ('已加载:', 'Chargé : '),
  ('加载失败', 'Échec du chargement'),
  ('复制', 'Copier'),
  ('已复制', 'Copié'),
  # Slash
  ('状态', 'État'),
  ('会话', 'Sessions'),
  ('管理', 'Gestion'),
  ('选项', 'Options'),
  ('工具', 'Outils'),
  ('媒体', 'Média'),
  ('Skills', 'Compétences'),
  ('其他', 'Divers'),
]

# Top-level filters: files we only patch superficial strings in
TARGETS = ['tsx', 'ts']

# Build a single regex that matches all source Chinese anywhere (2+ chars)
# We allow matching in JSX text or string literals. Both replaced with French.

def replace_in_file(path: str) -> int:
    with open(path, encoding='utf-8') as f:
        src = f.read()
    orig = src
    # Direct ordered replacements
    for src_str, dst in TR:
        src = src.replace(src_str, dst)
    # Generic Chinese blocks: ZH characters inside JSX text, mapped heuristically
    if not src.endswith('\n'):
        # leave it
        pass
    # Remove leftover Chinese 2+ characters by replacing with empty (or comment)
    src = re.sub(r"[一-鿿]{2,}", lambda m: '/*traduire*/', src)
    if src != orig:
        with open(path, 'w', encoding='utf-8') as f:
            f.write(src)
        return 1
    return 0

count = 0
for dp, dn, fn in os.walk(ROOT):
    if any(x in dp for x in ('node_modules', 'dist', 'build')):
        continue
    for f in fn:
        if f.endswith(('.tsx', '.ts')):
            p = os.path.join(dp, f)
            if replace_in_file(p):
                count += 1
                print(f'patched {p}')
print(f'\nTotal patched: {count}')
